Repository elixir-europe/rdmkit, pull requests merged in 2020-10, with the labels that each got.

#103 Adding a style guide page
  _data/sidebars/contribute.yml
  pages/contribute/style_guide.md
Labels: new page request

#106 Design tweaks
  _data/strings.yml
  css/customstyles.css
  index.md
  js/customscripts.js
  js/toc.js
  pages/contribute/style_guide.md
Labels: enhancement

#199 General changes
  _data/sidebars/main.yml
  _data/tags.yml
  _data/tool_and_resource_list.xlsx
  _data/tool_and_resource_list.yml
  _layouts/page.html
  css/customstyles.css
Labels: UI-UX, enhancement
